name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update submodules
      run: git submodule update --init
    - name: make
      run: make
    - name: test
      run: tests/json_test
